"use client";
import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, MapPin, Menu, Pause, Phone, Play, ShieldCheck, X } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const phone="8220800499";
export const wa=`https://wa.me/91${phone}?text=Hello%20Vijay%20Dental%2C%20I%20would%20like%20to%20book%20an%20appointment.`;
const nav=[['Home','/'],['Treatments','/treatments'],['About','/about'],['Your visit','/doctors'],['Studio gallery','/gallery'],['Blog','/blog'],['Contact','/contact']];
export function Logo(){return <Link href="/" className="logo" aria-label="Vijay Dental home"><span className="logo-mark">V</span><span><b>VIJAY</b><small>DENTAL STUDIO</small></span></Link>}
export function Header(){const [open,setOpen]=useState(false);return <header><div className="nav-wrap"><Logo/><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu" aria-expanded={open}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(([n,h])=><Link key={h} href={h} onClick={()=>setOpen(false)}>{n}</Link>)}<Link className="nav-cta" href="/appointment">Book appointment</Link></nav></div></header>}
export function Footer(){return <footer><div className="footer-grid"><div><Logo/><p>Modern dentistry, thoughtful care and confident smiles—under one roof in Chennai.</p></div><div><h4>Explore</h4>{nav.slice(0,5).map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><h4>Visit us</h4><p>Chennai, Tamil Nadu</p><p>Contact us for available appointment times</p><a href={`tel:+91${phone}`}>+91 82208 00499</a></div><div><h4>Need an appointment?</h4><p>Message our care team for available slots.</p><a href={wa} target="_blank" className="footer-btn">WhatsApp us <ArrowRight size={16}/></a></div></div><div className="copyright">© 2026 Vijay Dental Studio · Design preview. Illustrative stock photography; clinic details and services require confirmation.</div></footer>}
export function Shell({children}:{children:ReactNode}){return <><Header/><main>{children}</main><a className="float-wa" href={wa} target="_blank" aria-label="WhatsApp Vijay Dental">WA</a><Footer/></>}

const slides=[
 {image:'/images/studio.webp',eyebrow:'WELCOME TO VIJAY DENTAL',title:<>Your smile.<br/>Our thoughtful<br/><em>approach.</em></>,copy:'From everyday care to the changes you have been considering. A conversation is a good place to begin.'},
 {image:'/images/smile.webp',eyebrow:'A SMILE THAT FEELS LIKE YOU',title:<>A little change.<br/>A new sense of<br/><em>confidence.</em></>,copy:'Explore the possibilities for your smile, with time to understand your options and decide what feels right.'},
 {image:'/images/care.webp',eyebrow:'START WITH A CONVERSATION',title:<>Good questions.<br/>Clear choices.<br/><em>Better care.</em></>,copy:'Talk about your concerns, ask questions and understand the next step.'}
];
function Hero(){
 const [i,setI]=useState(0);const [paused,setPaused]=useState(true);const [visible,setVisible]=useState(true);
 useEffect(()=>{const preference=window.matchMedia('(prefers-reduced-motion: reduce)');setPaused(preference.matches);const visibility=()=>setVisible(!document.hidden);const reduced=()=>{if(preference.matches)setPaused(true)};visibility();document.addEventListener('visibilitychange',visibility);preference.addEventListener('change',reduced);return()=>{document.removeEventListener('visibilitychange',visibility);preference.removeEventListener('change',reduced)}},[]);
 useEffect(()=>{if(paused||!visible)return;const t=setInterval(()=>setI(v=>(v+1)%slides.length),7000);return()=>clearInterval(t)},[paused,visible,i]);
 const move=(direction:number)=>setI(v=>(v+direction+slides.length)%slides.length);
 return <section className="hero" aria-roledescription="carousel" aria-label="Dental studio highlights" onKeyDown={e=>{if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)}}>
 {slides.map((s,x)=><div key={s.image} role="group" aria-roledescription="slide" aria-label={`${x+1} of ${slides.length}`} aria-hidden={x!==i} inert={x!==i} className={`hero-slide ${x===i?'active':''}`} style={{backgroundImage:`linear-gradient(90deg,rgba(22,31,26,.85),rgba(22,31,26,.44) 55%,rgba(22,31,26,.08)),url(${s.image})`}}><div className="hero-copy"><span>{s.eyebrow}</span><h1>{s.title}</h1><p>{s.copy}</p><div className="hero-actions"><Link href="/appointment" className="btn primary">Arrange a consultation <ArrowRight size={18}/></Link><Link href="/treatments" className="btn glass">Explore dental care</Link></div></div></div>)}
 <button className="slide-arrow left" onClick={()=>move(-1)} aria-label="Previous slide"><ChevronLeft/></button><button className="slide-arrow right" onClick={()=>move(1)} aria-label="Next slide"><ChevronRight/></button><div className="dots">{slides.map((_,x)=><button key={x} className={i===x?'active':''} onClick={()=>setI(x)} aria-label={`Show slide ${x+1}`} aria-current={i===x}><span>{String(x+1).padStart(2,'0')}</span></button>)}<button className="slideshow-pause" onClick={()=>setPaused(v=>!v)} aria-label={paused?'Play slideshow':'Pause slideshow'}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'Play':'Pause'}</span></button></div>
 <div className="hero-note"><Phone/><span><b>Let’s talk</b>Enquire about your next visit</span><a href={`tel:+91${phone}`}>Call us</a></div></section>
}

const treatments=[
 ['Preventive Dentistry','Routine check-ups, gentle cleaning and personalised prevention plans.','01','/images/care.webp'],
 ['Root Canal Care','Comfort-focused care to save natural teeth and relieve dental pain.','02','/images/studio.webp'],
 ['Dental Implants','Strong, natural-looking tooth replacement planned with precision.','03','/images/smile.webp'],
 ['Braces & Aligners','Modern orthodontic options for a healthier, more confident smile.','04','/images/care.webp'],
 ['Smile Makeovers','A considered combination of whitening, veneers and reshaping.','05','/images/studio.webp'],
 ['Kids Dentistry','Patient, positive dental visits designed around young smiles.','06','/images/smile.webp']
];
export function HomePage(){return <Shell><Hero/><section className="intro section"><div><span className="kicker">WELCOME TO VIJAY DENTAL</span><h2>There’s a person<br/>behind every <em>smile.</em></h2></div><div><p>Sometimes you know exactly what you need. Sometimes you are looking for answers. Start with your concerns, explore the care options and bring the questions that matter to you.</p><Link href="/about" className="text-link">Discover our approach <ArrowRight/></Link></div></section><section className="services section"><div className="section-head"><div><span className="kicker">CARE FOR EVERY SMILE</span><h2>Care, around you.</h2></div><Link href="/treatments" className="text-link">View all treatments <ArrowRight/></Link></div><div className="service-grid home-treatment-grid">{treatments.slice(0,4).map(([n,d,num,img])=><article key={n}><div className="service-thumb" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(10,26,43,.5)),url(${img})`}}><span>{num}</span></div><div className="service-body"><h3>{n}</h3><p>{d}</p><Link href="/treatments">Explore care <ArrowRight/></Link></div></article>)}</div></section><section className="blog-preview section"><div className="section-head"><div><span className="kicker">DENTAL NOTES</span><h2>Small reads for healthier smiles.</h2></div><Link href="/blog" className="text-link">Read all articles <ArrowRight/></Link></div><div className="post-grid">{posts.slice(0,3).map(p=><article key={p.title}><span>{p.tag}</span><h3>{p.title}</h3><p>{p.excerpt}</p><Link href="/blog">Read article <ArrowRight/></Link></article>)}</div></section><FinalCTA/></Shell>}
export function PageHero({kicker,title,copy}:any){return <section className="page-hero"><span className="kicker light">{kicker}</span><h1>{title}</h1><p>{copy}</p></section>}
export function FinalCTA(){return <section className="final-cta"><span>READY WHEN YOU ARE</span><h2>Let’s make your next dental visit feel different.</h2><div><Link href="/appointment" className="btn primary">Request an appointment <ArrowRight/></Link><a href={`tel:+91${phone}`} className="btn outline">Call +91 82208 00499</a></div></section>}
export function TreatmentsPage(){return <Shell><PageHero kicker="OUR TREATMENTS" title="Care designed around your smile." copy="Explore thoughtful, modern treatment options with a clear path from consultation to confident care."/><section className="treatment-editorial section">{treatments.map(([n,d,num,img],i)=><article key={n} className={i%2?'reverse':''}><div className="treatment-photo" style={{backgroundImage:`linear-gradient(180deg,transparent 55%,rgba(10,26,43,.42)),url(${img})`}}><span>{num}</span><b>Vijay Dental Care</b></div><div className="treatment-copy"><span className="kicker">PERSONALISED TREATMENT · {num}</span><h2>{n}</h2><p>{d} Every plan begins with a detailed consultation, modern assessment and a clear explanation of every suitable option.</p><div className="treatment-benefits"><span><Check/>Clear consultation</span><span><Check/>Comfort-focused care</span><span><Check/>Personal treatment plan</span></div><div className="treatment-actions"><Link href="/appointment" className="btn dark">Book consultation <ArrowRight/></Link><a href={`https://wa.me/91${phone}?text=${encodeURIComponent(`Hello Vijay Dental, I would like to enquire about ${n}.`)}`} target="_blank" className="text-link">Ask about this treatment</a></div></div></article>)}</section><FinalCTA/></Shell>}
export function AboutPage(){return <Shell><PageHero kicker="OUR STORY" title="Dentistry built on trust, not pressure." copy="A modern clinic experience where careful listening and clinical excellence belong together."/><section className="split section"><div className="editorial-img clinic-img"/><div><span className="kicker">WHY VIJAY DENTAL</span><h2>We treat the person, not just the tooth.</h2><p>Vijay Dental was created to make quality dental care feel clearer and more personal. We believe patients deserve enough time to understand their oral health, ask questions and make confident decisions.</p><p>Our approach combines evidence-based dentistry, modern technology and an atmosphere designed to help every patient feel at ease.</p><div className="values">{[['Listen first','Every concern deserves attention.'],['Explain clearly','Know your options before you decide.'],['Care precisely','Thoughtful planning at every step.']].map(([a,b])=><div key={a}><Check/><p><b>{a}</b><span>{b}</span></p></div>)}</div></div></section><FinalCTA/></Shell>}
export function DoctorsPage(){return <Shell><PageHero kicker="YOUR FIRST VISIT" title="A little more understanding. A little less worry." copy="You do not need to arrive with all the answers. Bring your concerns and the questions you would like to ask."/><section className="doctor section"><div className="doctor-photo" role="img" aria-label="Illustrative dental consultation"/><div><span className="kicker">BEFORE YOUR CONSULTATION</span><h2>Bring your questions.</h2><p>Bring previous dental records if you have them. Share your current medications and relevant medical history with the treating clinician.</p><div className="values">{[['Discuss your concern','Explain what brought you in.'],['Understand your options','Ask about the findings and suitable choices.'],['Know the next step','Discuss the estimate, follow-up and alternatives.']].map(([a,b])=><div key={a}><Check/><p><b>{a}</b><span>{b}</span></p></div>)}</div><Link href="/appointment" className="btn dark">Enquire about a consultation <ArrowRight/></Link></div></section></Shell>}
const gallery=[['A place for conversation','/images/studio.webp'],['A personal approach','/images/smile.webp'],['Everyday dental care','/images/care.webp']];
export function GalleryPage(){return <Shell><PageHero kicker="VISUAL DIRECTION" title="A closer look at the studio concept." copy="Illustrative dental photography for this design preview. These images do not show Vijay Dental, its clinicians or patient results."/><section className="gallery section">{gallery.map(([x,img],i)=><article key={x}><div className="gallery-photo" role="img" aria-label={`Illustrative stock photo: ${x}`} style={{backgroundImage:`linear-gradient(180deg,transparent 45%,rgba(22,31,26,.62)),url(${img})`}}><span>0{i+1} / STUDIO CONCEPT</span></div><h3>{x}</h3><p>Illustrative stock photography.</p></article>)}</section><FinalCTA/></Shell>}
export const posts=[{tag:'PREVENTION',title:'How often should you really visit a dentist?',excerpt:'A simple guide to routine check-ups and why timing can differ for every smile.'},{tag:'ROOT CANAL',title:'Does a root canal treatment have to be painful?',excerpt:'What modern pain management and careful planning can change about the experience.'},{tag:'ALIGNERS',title:'Clear aligners or braces: what should you consider?',excerpt:'A practical look at comfort, discipline, complexity and treatment goals.'},{tag:'IMPLANTS',title:'What makes someone suitable for a dental implant?',excerpt:'The key oral-health factors your dentist evaluates before recommending implants.'},{tag:'CHILDREN',title:'Helping your child feel comfortable at the dentist',excerpt:'Small things parents can do before and during a young patient’s first visit.'},{tag:'EVERYDAY CARE',title:'Five brushing mistakes that are easy to fix',excerpt:'Simple adjustments that can make daily oral care more effective.'}];
export function BlogPage(){return <Shell><PageHero kicker="THE DENTAL JOURNAL" title="Useful guidance, written simply." copy="Practical dental information to help patients understand their oral health and make confident care decisions."/><section className="post-grid full section">{posts.map((p,i)=><article key={p.title} className={i===0?'featured':''}><span>{p.tag}</span><h2>{p.title}</h2><p>{p.excerpt}</p><a href={wa} target="_blank">Ask the dentist <ArrowRight/></a></article>)}</section></Shell>}
export function ContactPage(){return <Shell><PageHero kicker="CONTACT & APPOINTMENTS" title="Your visit starts with a simple message." copy="Call, WhatsApp or find us on the map. Our care team will help you choose a convenient appointment slot."/><section className="contact section"><div><span className="kicker">GET IN TOUCH</span><h2>We’re here to help.</h2>{[[Phone,'+91 82208 00499'],[MapPin,'Chennai, Tamil Nadu'],[CalendarDays,'Enquire about available dates'],[Clock3,'Confirm opening hours before travelling']].map(([I,t]:any)=><div className="contact-row" key={t}><I/><span>{t}</span></div>)}<a href={wa} target="_blank" className="btn dark">Message on WhatsApp <ArrowRight/></a></div><div className="map"><div className="location-note"><MapPin size={34}/><h3>Plan your visit.</h3><p>Contact the studio for the exact location and available appointment times.</p><a href={`tel:+91${phone}`} className="text-link">Call to enquire <ArrowRight/></a></div></div></section><FinalCTA/></Shell>}

export function AppointmentPage(){const [sent,setSent]=useState(false);const [treatment,setTreatment]=useState('');const [patient,setPatient]=useState('');if(sent)return <Shell><section className="success-page"><div><span className="success-icon"><Check/></span><span className="kicker">PREVIEW COMPLETE</span><h1>That’s the first step.</h1><p>This demonstration has not sent, saved or booked anything. Use the contact links to enquire about available times.</p><Link href="/" className="btn dark">Return to homepage <ArrowRight/></Link></div></section></Shell>;return <Shell><PageHero kicker="BOOK AN APPOINTMENT" title="Choose a time that works for you." copy="Explore the appointment request flow using sample details. This is a design preview; requests are not sent or stored."/><section className="booking section"><aside><span className="kicker">WHAT HAPPENS NEXT</span><h2>Simple, clear and pressure-free.</h2>{[['01','Submit your preferred date and time'],['02','Our clinic checks availability'],['03','We call you to confirm the visit']].map(([n,t])=><div className="booking-step" key={n}><b>{n}</b><span>{t}</span></div>)}<div className="booking-note"><Clock3/><p><b>Need urgent help?</b>Call <a href={`tel:+91${phone}`}>+91 82208 00499</a></p></div></aside><form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-head"><span>APPOINTMENT REQUEST</span><p>Fields marked * are required</p></div><div className="form-grid"><label>Full name *<input required name="name" placeholder="Your name"/></label><label>Mobile number *<input required name="phone" inputMode="tel" placeholder="10-digit number"/></label><label>Choose treatment *<Select required value={treatment} onValueChange={setTreatment}><SelectTrigger className="select-trigger"><SelectValue placeholder="Select a treatment"/></SelectTrigger><SelectContent>{treatments.map(([n])=><SelectItem key={n} value={n}>{n}</SelectItem>)}</SelectContent></Select></label><label>Patient type *<Select required value={patient} onValueChange={setPatient}><SelectTrigger className="select-trigger"><SelectValue placeholder="Choose one"/></SelectTrigger><SelectContent><SelectItem value="new">New patient</SelectItem><SelectItem value="existing">Existing patient</SelectItem></SelectContent></Select></label><label>Preferred date *<input required name="date" type="date"/></label><label>Preferred time *<input required name="time" type="time"/></label><label className="wide">Tell us anything helpful<textarea name="message" rows={4} placeholder="Pain, concern or preferred doctor (optional)"/></label></div><button className="submit-booking" type="submit">Preview request <ArrowRight/></button><p className="privacy-note"><ShieldCheck/>Demo only. Nothing is sent or saved. Use sample details.</p></form></section></Shell>}
